- app/views/admin/homes/top.html.erb
> [add]order/view/index

- app/controllers/admin/items_controller.rb
- app/controllers/public/homes_controller.rb
- app/controllers/public/items_controller.rb
- app/models/genre.rb
- app/models/item.rb
- app/views/admin/items/show.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- db/migrate/20241216023501_add_genre_id_to_items.rb
- db/schema.rb
> [finish]User-items-index-show

- app/controllers/admin/orders_controller.rb
- app/views/admin/orders/show.html.erb
- db/schema.rb
管理者の注文詳細ページです。
変数や処理は仮で置いています。
コントローラー部分も全て仮です。
> Feature order/view/show

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/cart_item.rb
- app/models/customer.rb
- app/models/item.rb
- app/views/admin/orders/show.html.erb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
- db/migrate/20241217061128_add_details_to_cart_items.rb
- db/schema.rb
カート機能です。
viewも整えてあります。
migrateあり
> Feature public/cart items

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/item.rb
- app/views/public/orders/complete.html.erb
- config/routes.rb
ユーザー:注文完了画面(サンクスページ)です。
cart_items/indexで同じ商品をカートに入れた時と同じ個数を選択して変更をした際のバグも修正しています。
migrateなし
> [add][fix] orders/complete, cart_items/index

- app/controllers/public/addresses_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/views/layouts/_header_public.html.erb
- app/views/public/addresses/edit.html.erb
- app/views/public/addresses/index.html.erb
- db/migrate/20241218015114_add_columns_to_addresses.rb
- db/schema.rb
・配送先登録・一覧
・配送先編集
・db:migrate必要です！
> Address index edit

- app/controllers/public/customers_controller.rb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
マイページ編集画面を作りました。
migrateとbundle installは必要ありません。
> Feature customers edit

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/javascript/stylesheets/application.scss
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/layouts/application.html.erb
・管理者側の会員一覧画面、会員詳細画面、会員登録内容の編集画面を作成しました。
・db:migrate不要です。
・昨日みっちーさんからコメントあったフッターの部分を調整しました。どのページでもページの下部に固定されて浮いてこないはずです。ご確認お願いします。
> Admin customers

- app/controllers/public/orders_controller.rb
- app/models/customer.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
- config/locales/ja.yml
- db/migrate/20241219020135_add_columns_to_orders.rb
- db/migrate/20241219020537_add_columns_to_order_details.rb
- db/schema.rb
注文機能です。
viewはそのままの部分が多いです。
migrateあり
> Feature order/function

- app/controllers/public/orders_controller.rb
- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
- config/locales/ja.yml
ユーザー:注文履歴詳細画面です。
ステータスに関連するenumも追加しています。
注文履歴一覧もenumに関連する部分を修正しています。
migrate なし
> [add] orders/show

- app/controllers/admin/homes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/models/order.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/initializers/kaminari_config.rb
管理者のtopページ(注文一覧)、管理者の注文詳細ページを実装しました。
migration なし
bundle install あり
> Feature admin/orders/function

- app/controllers/public/homes_controller.rb
- app/controllers/public/items_controller.rb
- app/views/public/genres/_genre_search.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
・ジャンル検索機能を実装
・publicのtopページ、商品一覧ページ、商品詳細ページにジャンル検索ボックスを作成
・renderでファイルひっぱってきています
・ジャンル検索を行っていないときは「商品一覧」と表示されるようになっています
・db:migrate不要
・gem追加なし
> Genres search

- app/javascript/stylesheets/application.scss
- app/views/admin/customers/index.html.erb
- app/views/admin/homes/top.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/public/items/index.html.erb
public/items/index
admin(管理者トップページ　注文履歴一覧画面)
/items/index
/customers/index
上記４ファイルのビューでページネーション作成。確認済。
> Pagenation

- app/views/admin/items/edit.html.erb
- app/views/admin/items/show.html.erb
- app/views/public/items/index.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
・細かい円表記のずれを修正しました
・ワイヤーフレームにあわせて、必要な個所にdelimiterを追記しました
> modified-yen

- app/views/admin/sessions/new.html.erb
- db/seeds.rb
管理者ログインページを編集しました
管理者のメールアドレスとパスワードを設定しました
rails db:seed が必要です
> Feature admin mail,password

- app/views/admin/homes/top.html.erb
- app/views/public/cart_items/index.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/orders/show.html.erb
・adminトップページの注文履歴一覧のenum表記正しました。
・その他細かいレイアウト調整しました。
> finish-i18n

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/homes_controller.rb
- app/controllers/admin/items_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/sessions_controller.rb
- app/controllers/public/addresses_controller.rb
- app/controllers/public/customers_controller.rb
- app/controllers/public/items_controller.rb
- app/controllers/public/orders_controller.rb
カスタマーと管理者の権限を追加しました。
migarte なし
bundle installなし
> [Add]authenticate_customer, authenticate_admin

- app/controllers/public/addresses_controller.rb
- app/controllers/public/customers_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/views/public/addresses/edit.html.erb
- app/views/public/addresses/index.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/sessions/new.html.erb
- app/views/public/shared/_error_messages.html.erb
- config/locales/ja.yml
パブリック側のバリデーションを作成しました。
bundle installとmigrateは必要ありません。
> Public validatation

- app/controllers/admin/sessions_controller.rb
- app/controllers/public/cart_items_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/layouts/_header_admin.html.erb
- app/views/layouts/application.html.erb
- app/views/public/cart_items/index.html.erb
修正項目
管理者のサインアウト時のURLを変更
管理者ログイン時のヘッダーを変更
カートが空の際に"情報入力へ進む"ボタンを非表示にした。
カートが空の状態で注文を作成できなくした。
migrate なし
> Feature bugfix yuki yoshizawa

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/items_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/public/addresses_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/models/genre.rb
- app/models/item.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/admin/shared/_error_messages.html.erb
- app/views/layouts/_flash_message.html.erb
- app/views/layouts/application.html.erb
- app/views/public/addresses/index.html.erb
- app/views/public/sessions/new.html.erb
- app/views/public/shared/_error_messages.html.erb
- config/locales/ja.yml
管理者側のバリデーションの設定
エラーメッセージとフラッシュメッセージの編集
migrateとbundle installは必要ありません
> Admin validation

- app/controllers/public/items_controller.rb
- app/views/public/items/show.html.erb
> [fix] items/controller items/showw

- app/views/public/orders/new.html.erb
> [fix] orders/new

- app/controllers/public/orders_controller.rb
- app/models/order.rb
注文情報入力画面で住所を未入力の場合画面が遷移しないようにした。
> [fix] orders/controller

- app/views/public/orders/new.html.erb
> [fix] public/orders/new

- app/controllers/admin/order_details_controller.rb
- app/controllers/public/cart_items_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/customer.rb
- app/models/order.rb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/registrations/new.html.erb
バリデーションの修正とフラッシュメッセージを修正しました。
migrateとbundle installは必要ありません。
> Add validation
